logging:
    level:
        ROOT: DEBUG
spring:
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml
    jpa:
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:mysql://${DEMO_DB_URL:localhost}:3306/demo
        username: dragos
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
client:
    demo2:
        url: ${DEMO2_URL:http://localhost:8181}